### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by radjivF** [tellnes/geolocation#1]
Hey, I'm trying to use your module and I got this error

```
ReferenceError: navigator is not defined
    at EventEmitter.exports.getCurrentPosition (/Users/radjiv/Documents/workspace/coding-task/node_modules/geolocation/index.js:41:3)
    at /Users/radjiv/Documents/workspace/coding-task/routes/index.js:12:15
```

if you have any ideas,
Thanks

**Comment by tellnes** [comment]
It should probably have been stated in the readme, but this module is intended to be used in the browser. Eg. with browserify.
